name: Deployment Workflow
on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Application
    uses: ./.github/workflows/development.yml

  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist

  deploy:
    name: Deploy Application to Github Pages
    runs-on: ubuntu-latest

    needs:
      - test
      - build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.0

      - name: Configure Github Pages
        uses: actions/configure-pages@v5.0.0

      - name: Download build artifact
        uses: actions/download-artifact@v4.1.8

      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4.0.5
